services:
  postgres:
    image: postgres:15
    container_name: ekko_postgres
    environment:
      POSTGRES_USER: charl
      POSTGRES_PASSWORD: charl
      POSTGRES_DB: ekko_roles
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=ekko_roles

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000

volumes:
  postgres_data: